### ISSUE TITLE
After projection, only black values found

### ISSUE THREAD

**Issue by hcwinsemius** [localdevices/pyorc#164]
### How did you install pyopenrivercam (mamba / conda or  pip)

pip

### What is the problem?

After certain transformations and projection, images are entirely black, causing no results in the velocimetry.

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a video, if possible include a copy of your dataset uploaded on Dropbox, Google Drive, or other)

For frames, use the following settings
```yaml
{
 "frames": {
    "time_diff": {
      "thres": 5
    },
    "minmax": {
      "min": 5
    },
    "project": {
      "method": "numpy"
    }
  }
}
```
This only occurs irregularly with specific videos.
